EXPERIMENT 4:Write a python program to import and export data using Pandas and
show the details of the dataset like number of rows, columns, first five
rows, size, number of missing values, sum, average, min and max
values from the numerical columns.

In [2]:
import pandas as pd

In [3]:
from google.colab import files

In [4]:
uploaded = files.upload()

Saving attendance.csv to attendance.csv

In [5]:
import io

In [7]:
 df = pd.read_csv(io.BytesIO(uploaded['attendance.csv'])) #reading a csv file

In [8]:
df.head(7) #to read first 7 elments

,ROLL ID,SAP ID,NAME,Mobile No.,Jan,Feb,March,Apr,May
0,R211235456,50002354,Pranav Sharma,2195275467,90%,75%,75%,100%,79%
1,R215665563,50003546,Ranjan Kumar,3458681667,85%,55%,65%,45%,67%
2,R218999654,50007894,Riya Srivastav,6355230652,80%,76%,89%,55%,90%
3,R212256653,50003156,Aditi Tamta,5199011174,75%,89%,97%,89%,67%
4,R218656723,50007235,Mehak Kandpal,9400440148,95%,88%,100%,89%,100%
5,R212544582,50002324,Sajal Suyal,5480911851,58%,90%,77%,66%,55%
6,R218946821,50008943,Lokesh Kapkoti,5322590673,80%,69%,95%,45%,89.50%

In [9]:
df.isnull() # to check wheter there is a null value or not represented by True or False

   ROLL ID  SAP ID   NAME  Mobile No.    Jan    Feb  March    Apr    May
0    False   False  False       False  False  False  False  False  False
1    False   False  False       False  False  False  False  False  False
2    False   False  False       False  False  False  False  False  False
3    False   False  False       False  False  False  False  False  False
4    False   False  False       False  False  False  False  False  False
5    False   False  False       False  False  False  False  False  False
6    False   False  False       False  False  False  False  False  False
7    False   False  False       False  False  False  False  False  False
8    False   False  False       False  False  False  False  False  False

In [10]:
df.isnull().sum() # to show the sum of the null value

ROLL ID       0
SAP ID        0
NAME          0
Mobile No.    0
Jan           0
Feb           0
March         0
Apr           0
May           0
dtype: int64

In [11]:
df.describe() # to count the mean, max and min value of the given csv file

             SAP ID    Mobile No.
count  9.000000e+00  9.000000e+00
mean   5.000454e+07  4.968988e+09
std    2.682305e+03  2.114684e+09
min    5.000232e+07  2.195275e+09
25%    5.000236e+07  3.458682e+09
50%    5.000316e+07  5.199011e+09
75%    5.000724e+07  5.480912e+09
max    5.000894e+07  9.400440e+09

In [12]:
df.tail(7) # to print last 7 elemnts of the csv file

,ROLL ID,SAP ID,NAME,Mobile No.,Jan,Feb,March,Apr,May
2,R218999654,50007894,Riya Srivastav,6355230652,80%,76%,89%,55%,90%
3,R212256653,50003156,Aditi Tamta,5199011174,75%,89%,97%,89%,67%
4,R218656723,50007235,Mehak Kandpal,9400440148,95%,88%,100%,89%,100%
5,R212544582,50002324,Sajal Suyal,5480911851,58%,90%,77%,66%,55%
6,R218946821,50008943,Lokesh Kapkoti,5322590673,80%,69%,95%,45%,89.50%
7,R219756894,50003013,Diwakar Bisht,3239190309,70%,50%,80%,89%,56%
8,R218656595,50002364,Devank Rathore,4069562366,69%,89%,60%,99%,89%

In [32]:
months = ['Jan', 'Feb', 'March', 'Apr', 'May']# Convert percentage strings to float values
for month in months:
    df[month] = df[month].astype(str).str.rstrip('%').astype('float') / 100.0
df['Avg'] = (df[months].mean(axis=1))*100 # To find the avg value entered in the present csv file

In [34]:
# Print monthly average percentages
print("Monthly Average Percentages:")
print(df[['SAP ID','ROLL ID', 'NAME', 'Avg']])

Monthly Average Percentages:
     SAP ID     ROLL ID            NAME       Avg
0  50002354  R211235456   Pranav Sharma  0.000008
1  50003546  R215665563    Ranjan Kumar  0.000006
2  50007894  R218999654  Riya Srivastav  0.000008
3  50003156  R212256653     Aditi Tamta  0.000008
4  50007235  R218656723   Mehak Kandpal  0.000009
5  50002324  R212544582     Sajal Suyal  0.000007
6  50008943  R218946821  Lokesh Kapkoti  0.000008
7  50003013  R219756894   Diwakar Bisht  0.000007
8  50002364  R218656595  Devank Rathore  0.000008

In [35]:
df.min()# To find the minimum value present in the csv file

ROLL ID        R211235456
SAP ID           50002324
NAME          Aditi Tamta
Mobile No.     2195275467
Jan                   0.0
Feb                   0.0
March                 0.0
Apr                   0.0
May                   0.0
Avg              0.000006
dtype: object

In [36]:
df.max()# To find the maximum value present in the csv file

ROLL ID        R219756894
SAP ID           50008943
NAME          Sajal Suyal
Mobile No.     9400440148
Jan                   0.0
Feb                   0.0
March                 0.0
Apr                   0.0
May                   0.0
Avg              0.000009
dtype: object

In [37]:
df.sum() #Sum of numerical columns

ROLL ID       R211235456R215665563R218999654R212256653R21865...
SAP ID                                                450040829
NAME          Pranav SharmaRanjan KumarRiya SrivastavAditi T...
Mobile No.                                          44720894307
Jan                                                    0.000001
Feb                                                    0.000001
March                                                  0.000001
Apr                                                    0.000001
May                                                    0.000001
Avg                                                     0.00007
dtype: object